In [10]:
import numpy as np

# create an array

a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
print(type(a))

# 2D Array

b= np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))
b.shape

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


(2, 3)

In [14]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [ ]:
np.eye(3)  # Diagonal Array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [29]:
# Array Properties

# 1) Shape

arr=np.array([[1,2,3,3.5],[4,5,6,6.5],[7,8,9,10]])
print(arr.shape)  # Number of rows and column

# 2) Size

print(arr.size)  # how many item are present in array

# 3) Dimention
print(arr.ndim)  # it tells the array is 1D,2D either 3D

# 4) Datatype
print(arr.dtype)  # it tells the data type of array

(3, 4)
12
2
float64


In [36]:
# Reshape 

arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr)

reshape=arr.reshape((3,2))
print(reshape)

(2, 3)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [42]:
# Indexing & Slicing

arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

newarr=arr.flatten()
print(newarr)

newarr[4]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


np.int64(5)

In [43]:
arr[3:]

array([[10, 11, 12]])

In [45]:
#  fancy indexing

arr=np.array([10,20,30,40,50,60])
idx=[0,5,2]
print(arr[idx])

[10 60 30]


In [46]:
#Boolean Masking---we can give a condition for an array

mask=arr>25
print(arr[mask])

[30 40 50 60]


In [47]:
# home work Que 

# create a 3x3 array filled with random numbers and print its shape

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)

(3, 3)


In [53]:
# Convert array into float 

arr1=np.array([1,2,3,4,5],dtype='float32')
print(type(arr1))
print(arr1)


<class 'numpy.ndarray'>
[1. 2. 3. 4. 5.]


In [55]:
#  reshape 1 D array into 3x3

arr2=np.array([1,2,3,4,5,6,7,8,9])
arr2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
# use boolean masking to find number grater than 5

num=arr2>5
print(arr2[num])

[6 7 8 9]


In [58]:
# Axis 

# 0=row 
# 1=column

arr=np.array([[1,2,3],[4,5,6]])
np.sum(arr,axis=0)

array([5, 7, 9])

In [59]:
np.sum(arr,axis=1)

array([ 6, 15])

In [61]:
arr[1][2]

np.int64(6)

In [65]:
num=np.array(range(1,101))
print(num)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [66]:
np.mean(num)

np.float64(50.5)

In [67]:
np.std(num)

np.float64(28.86607004772212)

In [68]:
np.var(num)

np.float64(833.25)

In [69]:
np.min(num)

np.int64(1)

In [70]:
np.max(num)

np.int64(100)

In [71]:
np.sum(num)

np.int64(5050)

In [72]:
np.prod(sum)

<function sum(iterable, /, start=0)>

In [73]:
np.median(num)

np.float64(50.5)

In [75]:
np.argmax(num)

np.int64(99)

In [76]:
np.argmin(num)

np.int64(0)

In [77]:
np.corrcoef(num)

np.float64(1.0)

In [78]:
np.unique(num)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [79]:
np.diff(num)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [80]:
np.cumsum(num)

array([   1,    3,    6,   10,   15,   21,   28,   36,   45,   55,   66,
         78,   91,  105,  120,  136,  153,  171,  190,  210,  231,  253,
        276,  300,  325,  351,  378,  406,  435,  465,  496,  528,  561,
        595,  630,  666,  703,  741,  780,  820,  861,  903,  946,  990,
       1035, 1081, 1128, 1176, 1225, 1275, 1326, 1378, 1431, 1485, 1540,
       1596, 1653, 1711, 1770, 1830, 1891, 1953, 2016, 2080, 2145, 2211,
       2278, 2346, 2415, 2485, 2556, 2628, 2701, 2775, 2850, 2926, 3003,
       3081, 3160, 3240, 3321, 3403, 3486, 3570, 3655, 3741, 3828, 3916,
       4005, 4095, 4186, 4278, 4371, 4465, 4560, 4656, 4753, 4851, 4950,
       5050])

In [84]:
np.log(num)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
       3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
       3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945,
       3.71357207, 3.73766962, 3.76120012, 3.78418963, 3.80666249,
       3.8286414 , 3.8501476 , 3.87120101, 3.8918203 , 3.91202301,
       3.93182563, 3.95124372, 3.97029191, 3.98898405, 4.00733319,
       4.02535169, 4.04305127, 4.06044301, 4.07753744, 4.09434456,
       4.11087386, 4.12713439, 4.14313473, 4.15888308, 4.17438727,
       4.18965474, 4.20469262, 4.21950771, 4.2341065 , 4.24849524,
       4.26267988, 4.27666612, 4.29045944, 4.30406509, 4.31748

In [85]:
np.exp(num)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13, 2.90488497e+13, 7.89629602e+13,
       2.14643580e+14, 5.83461743e+14, 1.58601345e+15, 4.31123155e+15,
       1.17191424e+16, 3.18559318e+16, 8.65934004e+16, 2.35385267e+17,
       6.39843494e+17, 1.73927494e+18, 4.72783947e+18, 1.28516001e+19,
       3.49342711e+19, 9.49611942e+19, 2.58131289e+20, 7.01673591e+20,
       1.90734657e+21, 5.18470553e+21, 1.40934908e+22, 3.83100800e+22,
       1.04137594e+23, 2.83075330e+23, 7.69478527e+23, 2.09165950e+24,
      